# coding: utf-8

"""

    Manages devices through Devicelink.   # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.device_info_model import DeviceInfoModel  # noqa: E501
from openapi_client.rest import ApiException


class TestDeviceInfoModel(unittest.TestCase):
    """DeviceInfoModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeviceInfoModel(self):
        """Test DeviceInfoModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.device_info_model.DeviceInfoModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
