# coding: utf-8

"""
    Cloud IoT

    Registers and manages IoT (Internet of Things) devices that connect to the Google Cloud Platform.   # noqa: E501

    OpenAPI spec version: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.projects_api import ProjectsApi  # noqa: E501
from openapi_client.rest import ApiException


class TestProjectsApi(unittest.TestCase):
    """ProjectsApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.projects_api.ProjectsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cloudiot_projects_locations_registries_create(self):
        """Test case for cloudiot_projects_locations_registries_create

        """
        pass

    def test_cloudiot_projects_locations_registries_devices_config_versions_list(self):
        """Test case for cloudiot_projects_locations_registries_devices_config_versions_list

        """
        pass

    def test_cloudiot_projects_locations_registries_devices_create(self):
        """Test case for cloudiot_projects_locations_registries_devices_create

        """
        pass

    def test_cloudiot_projects_locations_registries_devices_delete(self):
        """Test case for cloudiot_projects_locations_registries_devices_delete

        """
        pass

    def test_cloudiot_projects_locations_registries_devices_get(self):
        """Test case for cloudiot_projects_locations_registries_devices_get

        """
        pass

    def test_cloudiot_projects_locations_registries_devices_list(self):
        """Test case for cloudiot_projects_locations_registries_devices_list

        """
        pass

    def test_cloudiot_projects_locations_registries_devices_modify_cloud_to_device_config(self):
        """Test case for cloudiot_projects_locations_registries_devices_modify_cloud_to_device_config

        """
        pass

    def test_cloudiot_projects_locations_registries_devices_patch(self):
        """Test case for cloudiot_projects_locations_registries_devices_patch

        """
        pass

    def test_cloudiot_projects_locations_registries_devices_states_list(self):
        """Test case for cloudiot_projects_locations_registries_devices_states_list

        """
        pass

    def test_cloudiot_projects_locations_registries_groups_get_iam_policy(self):
        """Test case for cloudiot_projects_locations_registries_groups_get_iam_policy

        """
        pass

    def test_cloudiot_projects_locations_registries_groups_set_iam_policy(self):
        """Test case for cloudiot_projects_locations_registries_groups_set_iam_policy

        """
        pass

    def test_cloudiot_projects_locations_registries_groups_test_iam_permissions(self):
        """Test case for cloudiot_projects_locations_registries_groups_test_iam_permissions

        """
        pass

    def test_cloudiot_projects_locations_registries_list(self):
        """Test case for cloudiot_projects_locations_registries_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
