# coding: utf-8

"""

    Manages devices through Devicelink.   # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.default_api import DefaultApi  # noqa: E501
from openapi_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_devicelink_add_device_to_group(self):
        """Test case for devicelink_add_device_to_group

        Adds device to group.  # noqa: E501
        """
        pass

    def test_devicelink_create_group(self):
        """Test case for devicelink_create_group

        Creates a device group.  # noqa: E501
        """
        pass

    def test_devicelink_delete_group(self):
        """Test case for devicelink_delete_group

        Deletes a group.  # noqa: E501
        """
        pass

    def test_devicelink_do_action(self):
        """Test case for devicelink_do_action

        Prompts a device action.  # noqa: E501
        """
        pass

    def test_devicelink_get_actions(self):
        """Test case for devicelink_get_actions

        Gets device actions.  # noqa: E501
        """
        pass

    def test_devicelink_get_data(self):
        """Test case for devicelink_get_data

        Gets device properties.  # noqa: E501
        """
        pass

    def test_devicelink_get_device_event(self):
        """Test case for devicelink_get_device_event

        Gets device events.  # noqa: E501
        """
        pass

    def test_devicelink_get_group_info(self):
        """Test case for devicelink_get_group_info

        Gets a device group.  # noqa: E501
        """
        pass

    def test_devicelink_get_groups(self):
        """Test case for devicelink_get_groups

        Gets device groups.  # noqa: E501
        """
        pass

    def test_devicelink_get_specific_action(self):
        """Test case for devicelink_get_specific_action

        Gets a device action.  # noqa: E501
        """
        pass

    def test_devicelink_remove_device_from_group(self):
        """Test case for devicelink_remove_device_from_group

        Removes device from a group.  # noqa: E501
        """
        pass

    def test_devicelink_update_group_metadata(self):
        """Test case for devicelink_update_group_metadata

        Updates group information.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
