# coding: utf-8

"""
    Cloud IoT

    Registers and manages IoT (Internet of Things) devices that connect to the Google Cloud Platform.   # noqa: E501

    OpenAPI spec version: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.registry_credential import RegistryCredential  # noqa: E501
from openapi_client.rest import ApiException


class TestRegistryCredential(unittest.TestCase):
    """RegistryCredential unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRegistryCredential(self):
        """Test RegistryCredential"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.registry_credential.RegistryCredential()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
