# coding: utf-8

"""
    Cloud IoT

    Registers and manages IoT (Internet of Things) devices that connect to the Google Cloud Platform.   # noqa: E501

    OpenAPI spec version: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.public_key_credential import PublicKeyCredential  # noqa: E501
from openapi_client.rest import ApiException


class TestPublicKeyCredential(unittest.TestCase):
    """PublicKeyCredential unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPublicKeyCredential(self):
        """Test PublicKeyCredential"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.public_key_credential.PublicKeyCredential()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
