# coding: utf-8

"""

    Manages devices through Devicelink.   # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.body2 import Body2  # noqa: E501
from openapi_client.rest import ApiException


class TestBody2(unittest.TestCase):
    """Body2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBody2(self):
        """Test Body2"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.body2.Body2()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
