# coding: utf-8

"""
    Cloud IoT

    Registers and manages IoT (Internet of Things) devices that connect to the Google Cloud Platform.   # noqa: E501

    OpenAPI spec version: v1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class MqttConfig(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'mqtt_enabled_state': 'str'
    }

    attribute_map = {
        'mqtt_enabled_state': 'mqttEnabledState'
    }

    def __init__(self, mqtt_enabled_state=None):  # noqa: E501
        """MqttConfig - a model defined in OpenAPI"""  # noqa: E501

        self._mqtt_enabled_state = None
        self.discriminator = None

        if mqtt_enabled_state is not None:
            self.mqtt_enabled_state = mqtt_enabled_state

    @property
    def mqtt_enabled_state(self):
        """Gets the mqtt_enabled_state of this MqttConfig.  # noqa: E501

        If enabled, allows connections using the MQTT protocol. Otherwise, MQTT connections to this registry will fail.  # noqa: E501

        :return: The mqtt_enabled_state of this MqttConfig.  # noqa: E501
        :rtype: str
        """
        return self._mqtt_enabled_state

    @mqtt_enabled_state.setter
    def mqtt_enabled_state(self, mqtt_enabled_state):
        """Sets the mqtt_enabled_state of this MqttConfig.

        If enabled, allows connections using the MQTT protocol. Otherwise, MQTT connections to this registry will fail.  # noqa: E501

        :param mqtt_enabled_state: The mqtt_enabled_state of this MqttConfig.  # noqa: E501
        :type: str
        """
        allowed_values = ["MQTT_STATE_UNSPECIFIED", "MQTT_ENABLED", "MQTT_DISABLED"]  # noqa: E501
        if mqtt_enabled_state not in allowed_values:
            raise ValueError(
                "Invalid value for `mqtt_enabled_state` ({0}), must be one of {1}"  # noqa: E501
                .format(mqtt_enabled_state, allowed_values)
            )

        self._mqtt_enabled_state = mqtt_enabled_state

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MqttConfig):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
