# coding: utf-8

"""
    Cloud IoT

    Registers and manages IoT (Internet of Things) devices that connect to the Google Cloud Platform.   # noqa: E501

    OpenAPI spec version: v1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class DeviceCredential(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'expiration_time': 'str',
        'public_key': 'PublicKeyCredential'
    }

    attribute_map = {
        'expiration_time': 'expirationTime',
        'public_key': 'publicKey'
    }

    def __init__(self, expiration_time=None, public_key=None):  # noqa: E501
        """DeviceCredential - a model defined in OpenAPI"""  # noqa: E501

        self._expiration_time = None
        self._public_key = None
        self.discriminator = None

        if expiration_time is not None:
            self.expiration_time = expiration_time
        if public_key is not None:
            self.public_key = public_key

    @property
    def expiration_time(self):
        """Gets the expiration_time of this DeviceCredential.  # noqa: E501

        [Optional] The time at which this credential becomes invalid. This credential will be ignored for new client authentication requests after this timestamp; however, it will not be automatically deleted.  # noqa: E501

        :return: The expiration_time of this DeviceCredential.  # noqa: E501
        :rtype: str
        """
        return self._expiration_time

    @expiration_time.setter
    def expiration_time(self, expiration_time):
        """Sets the expiration_time of this DeviceCredential.

        [Optional] The time at which this credential becomes invalid. This credential will be ignored for new client authentication requests after this timestamp; however, it will not be automatically deleted.  # noqa: E501

        :param expiration_time: The expiration_time of this DeviceCredential.  # noqa: E501
        :type: str
        """

        self._expiration_time = expiration_time

    @property
    def public_key(self):
        """Gets the public_key of this DeviceCredential.  # noqa: E501


        :return: The public_key of this DeviceCredential.  # noqa: E501
        :rtype: PublicKeyCredential
        """
        return self._public_key

    @public_key.setter
    def public_key(self, public_key):
        """Sets the public_key of this DeviceCredential.


        :param public_key: The public_key of this DeviceCredential.  # noqa: E501
        :type: PublicKeyCredential
        """

        self._public_key = public_key

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DeviceCredential):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
