# coding: utf-8

"""

    Manages devices through Devicelink.   # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class DevicePropertiesStatus(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'topic': 'DevicePropertiesStatusTopic',
        'predicate': 'DevicePropertiesStatusPredicate',
        'actions': 'DevicePropertiesStatusActions',
        'status': 'str'
    }

    attribute_map = {
        'topic': 'topic',
        'predicate': 'predicate',
        'actions': 'actions',
        'status': 'status'
    }

    def __init__(self, topic=None, predicate=None, actions=None, status=None):  # noqa: E501
        """DevicePropertiesStatus - a model defined in OpenAPI"""  # noqa: E501

        self._topic = None
        self._predicate = None
        self._actions = None
        self._status = None
        self.discriminator = None

        if topic is not None:
            self.topic = topic
        if predicate is not None:
            self.predicate = predicate
        if actions is not None:
            self.actions = actions
        if status is not None:
            self.status = status

    @property
    def topic(self):
        """Gets the topic of this DevicePropertiesStatus.  # noqa: E501


        :return: The topic of this DevicePropertiesStatus.  # noqa: E501
        :rtype: DevicePropertiesStatusTopic
        """
        return self._topic

    @topic.setter
    def topic(self, topic):
        """Sets the topic of this DevicePropertiesStatus.


        :param topic: The topic of this DevicePropertiesStatus.  # noqa: E501
        :type: DevicePropertiesStatusTopic
        """

        self._topic = topic

    @property
    def predicate(self):
        """Gets the predicate of this DevicePropertiesStatus.  # noqa: E501


        :return: The predicate of this DevicePropertiesStatus.  # noqa: E501
        :rtype: DevicePropertiesStatusPredicate
        """
        return self._predicate

    @predicate.setter
    def predicate(self, predicate):
        """Sets the predicate of this DevicePropertiesStatus.


        :param predicate: The predicate of this DevicePropertiesStatus.  # noqa: E501
        :type: DevicePropertiesStatusPredicate
        """

        self._predicate = predicate

    @property
    def actions(self):
        """Gets the actions of this DevicePropertiesStatus.  # noqa: E501


        :return: The actions of this DevicePropertiesStatus.  # noqa: E501
        :rtype: DevicePropertiesStatusActions
        """
        return self._actions

    @actions.setter
    def actions(self, actions):
        """Sets the actions of this DevicePropertiesStatus.


        :param actions: The actions of this DevicePropertiesStatus.  # noqa: E501
        :type: DevicePropertiesStatusActions
        """

        self._actions = actions

    @property
    def status(self):
        """Gets the status of this DevicePropertiesStatus.  # noqa: E501


        :return: The status of this DevicePropertiesStatus.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this DevicePropertiesStatus.


        :param status: The status of this DevicePropertiesStatus.  # noqa: E501
        :type: str
        """
        allowed_values = ["acked", "unknown"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"  # noqa: E501
                .format(status, allowed_values)
            )

        self._status = status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DevicePropertiesStatus):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
