# coding: utf-8

"""
    Cloud IoT

    Registers and manages IoT (Internet of Things) devices that connect to the Google Cloud Platform.   # noqa: E501

    OpenAPI spec version: v1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class PublicKeyCertificate(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'certificate': 'str',
        'format': 'str',
        'x509_details': 'X509CertificateDetails'
    }

    attribute_map = {
        'certificate': 'certificate',
        'format': 'format',
        'x509_details': 'x509Details'
    }

    def __init__(self, certificate=None, format=None, x509_details=None):  # noqa: E501
        """PublicKeyCertificate - a model defined in OpenAPI"""  # noqa: E501

        self._certificate = None
        self._format = None
        self._x509_details = None
        self.discriminator = None

        if certificate is not None:
            self.certificate = certificate
        if format is not None:
            self.format = format
        if x509_details is not None:
            self.x509_details = x509_details

    @property
    def certificate(self):
        """Gets the certificate of this PublicKeyCertificate.  # noqa: E501

        The certificate data.  # noqa: E501

        :return: The certificate of this PublicKeyCertificate.  # noqa: E501
        :rtype: str
        """
        return self._certificate

    @certificate.setter
    def certificate(self, certificate):
        """Sets the certificate of this PublicKeyCertificate.

        The certificate data.  # noqa: E501

        :param certificate: The certificate of this PublicKeyCertificate.  # noqa: E501
        :type: str
        """

        self._certificate = certificate

    @property
    def format(self):
        """Gets the format of this PublicKeyCertificate.  # noqa: E501

        The certificate format.  # noqa: E501

        :return: The format of this PublicKeyCertificate.  # noqa: E501
        :rtype: str
        """
        return self._format

    @format.setter
    def format(self, format):
        """Sets the format of this PublicKeyCertificate.

        The certificate format.  # noqa: E501

        :param format: The format of this PublicKeyCertificate.  # noqa: E501
        :type: str
        """
        allowed_values = ["UNSPECIFIED_PUBLIC_KEY_CERTIFICATE_FORMAT", "X509_CERTIFICATE_PEM"]  # noqa: E501
        if format not in allowed_values:
            raise ValueError(
                "Invalid value for `format` ({0}), must be one of {1}"  # noqa: E501
                .format(format, allowed_values)
            )

        self._format = format

    @property
    def x509_details(self):
        """Gets the x509_details of this PublicKeyCertificate.  # noqa: E501


        :return: The x509_details of this PublicKeyCertificate.  # noqa: E501
        :rtype: X509CertificateDetails
        """
        return self._x509_details

    @x509_details.setter
    def x509_details(self, x509_details):
        """Sets the x509_details of this PublicKeyCertificate.


        :param x509_details: The x509_details of this PublicKeyCertificate.  # noqa: E501
        :type: X509CertificateDetails
        """

        self._x509_details = x509_details

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PublicKeyCertificate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
